---
# tasks file for vim
- name: Install vim
  become: true
  ansible.builtin.package:
    name: vim
    state: present

- name: Path for RHEL-like OS's
  when: ansible_os_family == "RedHat"
  ansible.builtin.set_fact:
    vimrc_path: /etc/vimrc.local

- name: Copy vimrc.local file
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/vim/vimrc.local"
    dest: "{{ vimrc_path | default('/etc/vim/vimrc.local') }}"
    mode: '644'
